- name: ping playbook
  hosts: web
  tasks:
  - name: ping the server
    ansible.builtin.ping:



    #####execution
    ####ansible-playbook -i inventory.ini -e ansible_user=centos -e ansible_password=DevOps321 01-playbook.yaml