#-name: variables from PLAY level
- name: variables from PLAY level
  hosts: localhost
  tasks:
    - name: check variables
      ansible.builtin.debug:
        msg: "Hello{{Person}}, Good {{Wishes}}"


